name: Twitter Monitor Bot

on:
  schedule:
    - cron: "30 19,11,16 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
          TWITTER_HANDLE: ${{ secrets.TWITTER_HANDLE }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}

      - name: Commit updated count
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add last_count.txt
          git commit -m "Update last count" || echo "No changes"
          git push